### PR TITLE
Adding testcase for ".all()", ".any()" and ".parity()"

### PR DESCRIPTION
**Pull request by yaus**

### CODE REVIEW

**Comment by khwong-c** [comment]
Thanks for the contribution ☺️

I have no problem on the SV side, which is good.

As you might already recognize, Bit reduced AND is functionally equivalent to the `Signal.all()` ( and also `Signal.any()` to OR case)
I would recommend you simply replace my implementation on `.all(), .any()` syntax, without branching the the `reduce_or()`

- `any()` and `all()` are commonly understood by python programmer. we can say it out : If ALL bits of the signal is 1...

- They are shorter 😉

---

With the similar reason, can you think of a nice name for `reduce_xor()`? e.g. `parity()` or anything similar in python.

**Comment by yaus** [comment]
Ok. Let's fix it. 
It might be better to set some upcoming tasks for the project.

**Comment by khwong-c** [comment]
> It might be better to set some upcoming tasks for the project.

I agree. I just have a rough roadmap ATM.
I will put it on the README later on.

Documentation is also important in this work 🤦🏻

**Comment by khwong-c** [comment]
Ping me whenever this is ready for review. :)

**Comment by yaus** [comment]
@khwong-c The code is ready

**Pull request merged**
